# -*- coding: utf-8 -*-
"""assignment3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QTMoVHMPNq7-lErSj0ZuXKZ78Y2ZP5Fn

Question 1
"""

#This iterates over the integers from 1 to 18, not including 18 and determines if they are even or odd
#Then it prints the number with its classification
for i in range(1,18):
  if i%2==0:
    print(i,'is even.')
  else:
    print(i,'is odd.')

"""Question 2"""

#a prime number has 1 and itself as its only factors, but since all numbers have 1 and themselves as factors, need to check
#if other numbers have factors other than 1 and themselves
#counter only increases if number is prime until it reaches 5 (so first 5 prime printed)
def isPrime(y):
  i=2
  while i < y:
    if y%i == 0 :
      return 0
      exit()
    i=i+1
  return 1


count = 1
n = 2
while count <= 5:
  if isPrime(n) == 1:
    print(n)
    count +=1
  n=n+1