# -*- coding: utf-8 -*-
"""assignment2_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1prOwWxHCotS14pho-4f9_iFGkVky9TPk

Question 2
"""

#Checks if user input is a string,integer, or float
user_input = input('Give an example input.')
try:
  user_input = int(user_input)
  print("Your input was a number")
except ValueError:
  try:
    user_input = float(user_input)
    print("Your input was a float")
  except ValueError:
    print("Your input was a string")